Encryption doc updates
belaban/JGroups pull request #520
Opened 2020-11-06 16:34 UTC by oraNod

A couple things in encryption docs I found slightly misleading.

- SYM_ENCRYPT and ASYM_ENCRYPT need to go above NAKACK2.
- You can use other keystore formats with SYM_ENCRYPT with the keystore_type config attribute.

2020-11-09 14:44 UTC, belaban requested changes
Hi @oraNod 
No, the encryption protocols need to go _below_ NAKACK2!! Take a look at the sample configs.

2020-11-09 15:25 UTC, oraNod commented
> Hi @oraNod
> No, the encryption protocols need to go _below_ NAKACK2!! Take a look at the sample configs.

Thanks @belaban ! I thought you were going to hit on this. It's something I find slightly confusing. Bear with me if this is something that should be obvious of self-explanatory. I understand that the ordering matters so that NAKACK2 is also encrypted.

When I look at the example configs, it appears to me that the *_ENCRYPT protocols occur in the stack before NAKACK2. This is why it lead me to believe there was a typo (before = above). With the Infinispan docs, we use stack.combine="INSERT_BEFORE" like this:

```
<ASYM_ENCRYPT ... stack.combine="INSERT_BEFORE" stack.position="pbcast.NAKACK2"/>
```

Maybe I'm thinking about the order of the stack in the wrong way after looking at Infinispan configs.

I'll revert the changes in this PR but wanted to explain. Hopefully it makes sense and thank you for the corrections.

2020-11-09 15:27 UTC, belaban commented
Yes, this is confusing! I always talk about protocols wrt their position in the running stack, *not* the position in the config.
Note that I once wanted to change the config, to reflect the actual running stack, but this caused an uproar, as all configs would have had to be changed... :-)

2020-11-09 15:30 UTC, oraNod commented
I see. Thanks for explaining the background there! I've changed it back.

2020-11-09 15:37 UTC, belaban requested changes
Hi @oraNod 
I see a lot of whitespace changes.
Please don't update protocols.adoc *directly*! This is generated code, by looking at the protocols and grabbing all of the attributes. PropertiesToAsciidoc is used here...
So you need to edit the code directly. If you want, I can show you how to do this and then generate protocols.adoc

2020-11-10 10:09 UTC, oraNod commented
@belaban Thanks again for explaining how JGroups docs are built. I updated the PR to remove the commit with all those unintentional whitespace changes (it was my editor). 

I also looked into SYM_ENCRYPT.java to make sure I applied changes in the correct place and then did a local build. It seems like the changes I made are outside the generated docs.

2020-11-10 15:43 UTC, merged

2020-11-10 15:43 UTC, belaban commented
Thx Done!